name: Build and Publish to PyPI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['36', '37', '38', '39']

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set Up the Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install twine
      run: python -m pip install twine

    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Pull Docker image
      run: docker pull maydomine/bmtrain-manylinux:cu110

    - name: Run Docker image and execute script
      run: |
        version=${{ matrix.python-version }}
        docker run -e PATH="/workspace/cmake-3.26.4-linux-x86_64/bin:$PATH" -v ${{ github.workspace }}:/workspace/BMTrain -it maydomine/bmtrain-manylinux:cu110 /bin/bash -c "cd /workspace/BMTrain;/opt/python/cp${version}*/bin/python setup.py bdist_wheel -d ./dist/;/opt/python/cp${version}*/bin/python setup.py sdist -d ./dist/"

    - name: Publish to PyPI
      env:
        TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      run: |
        cd dist
        python -m twine upload --repository-url https://test.pypi.org/legacy/ *.tar.gz *.whl

