name: Build and Publish to PyPI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['36', '37', '38', '39']

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set Up the Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install twine
      run: python -m pip install twine

    - name: Run Docker image and execute script
      uses: addnab/docker-run-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        image: maydomine/bmtrain-manylinux:cu110
        option: -e PATH="/workspace/cmake-3.26.4-linux-x86_64/bin:/opt/rh/devtoolset-7/root/usr/bin/:$PATH" -e LD_LIBRARY_PATH="/opt/rh/devtoolset-7/root/usr/lib64:/opt/rh/devtoolset-7/root/usr/lib:/usr/local/nvidia/lib:/usr/local/nvidia/lib64:$LD_LIBRARY_PATH" -v ${{ github.workspace }}:/workspace/BMTrain
        shell: bash
        run: |
            version=${{ matrix.python-version }}
            cd /workspace/BMTrain
            /opt/python/cp${version}*/bin/python setup.py bdist_wheel -d ./dist/
            /opt/python/cp${version}*/bin/python setup.py sdist -d ./dist/

    - name: Publish to PyPI
      env:
        TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      run: |
        cd dist
        python -m twine upload --repository-url https://test.pypi.org/legacy/ *.tar.gz *.whl

