name: Build and Publish to PyPI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.6', '3.7', '3.8', '3.9']

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install twine
      run: python -m pip install twine

    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Pull Docker image
      run: docker pull maydomine/bmtrain-manylinux:cu110

    - name: Run Docker image and execute script
      run: |
        docker run -v ${{ github.workspace }}:/workspace/BMTrain maydomine/bmtrain-manylinux:cu110 /bin/bash -c "chmod +x /workspace/BMTrain/build.sh; /workspace/BMTrain/build.sh"
    - name: Remove dot from python version
      id: py-version
      run: echo "::set-output name=version::${{ replace(matrix.python-version, '.', '') }}"

    - name: Build source distribution
      run: docker run -v ${{ github.workspace }}:/workspace/BMTrain maydomine/bmtrain-manylinux:cu110 /bin/bash -c "cd /workspace/BMTrain; /opt/python/cp${{ steps.py-version.outputs.version }}*/bin/python setup.py sdist"

    - name: Publish to PyPI
      env:
        TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      run: |
        cd dist
        python -m twine upload --repository-url https://test.pypi.org/legacy/ *.tar.gz *.whl

