name: Build and Publish to PyPI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.6', '3.7', '3.8', '3.9']

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install twine
      run: python -m pip install twine

    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Pull Docker image
      run: docker pull maydomine/bmtrain-manylinux:cu110

    - name: Run Docker image and execute script
      run: |
        version=${{ matrix.python-version }}
        version=${version//./}
        alias python=/opt/python/cp${version}*/bin/python
        alias pip=/opt/python/cp${version}*/bin/pip
        docker run -v ${{ github.workspace }}:/workspace/BMTrain maydomine/bmtrain-manylinux:cu110 /bin/bash -c "pip install pybind11; pip install numpy;python setup.py bdist_wheel -d ./dist/;python setup.py sdist -d ./dist/"

    - name: Publish to PyPI
      env:
        TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      run: |
        cd dist
        python -m twine upload --repository-url https://test.pypi.org/legacy/ *.tar.gz *.whl

